language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'IonicMedicalApp' ]; then cd .. && eval "mv $currentfolder IonicMedicalApp" && cd IonicMedicalApp; fi
